package CapaDatos;
// Generated 10/07/2015 12:08:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comite generated by hbm2java
 */
@Entity
@Table(name="comite"
    ,catalog="procesosproyectofinaldb"
)
public class Comite  implements java.io.Serializable {


     private Integer idcomite;
     private Integer director;
     private Integer docente1;
     private Integer docente2;
     private Integer docente3;

    public Comite() {
    }

    public Comite(Integer director, Integer docente1, Integer docente2, Integer docente3) {
       this.director = director;
       this.docente1 = docente1;
       this.docente2 = docente2;
       this.docente3 = docente3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcomite", unique=true, nullable=false)
    public Integer getIdcomite() {
        return this.idcomite;
    }
    
    public void setIdcomite(Integer idcomite) {
        this.idcomite = idcomite;
    }

    
    @Column(name="director")
    public Integer getDirector() {
        return this.director;
    }
    
    public void setDirector(Integer director) {
        this.director = director;
    }

    
    @Column(name="docente1")
    public Integer getDocente1() {
        return this.docente1;
    }
    
    public void setDocente1(Integer docente1) {
        this.docente1 = docente1;
    }

    
    @Column(name="docente2")
    public Integer getDocente2() {
        return this.docente2;
    }
    
    public void setDocente2(Integer docente2) {
        this.docente2 = docente2;
    }

    
    @Column(name="docente3")
    public Integer getDocente3() {
        return this.docente3;
    }
    
    public void setDocente3(Integer docente3) {
        this.docente3 = docente3;
    }




}


